# render.yaml
services:
  - type: web
    name: your-service-name
    env: python
    buildCommand: |
      pip install --upgrade pip setuptools wheel
      pip install -r requirements.txt
    startCommand: python 
